### ISSUE TITLE
Multiple peel support

### ISSUE THREAD

**Issue by uxder** [andrewplummer/peel-js#1]
I would like to be able to fold and peel a given element multiple times.  

Example:  
- Fold a box once (and it's triangular)
- Then fold that triangle again and again.

Please add this feature!

**Comment by andrewplummer** [comment]
tl;dr

**Comment by uxder** [comment]
Ah man.....that hurts Andrew....

**Comment by andrewplummer** [comment]
Haha sorry... bad joke.

What if you did something like this... initiate a peel, then when the peel effect has finished, reinitialize a new peel effect with the input being the result of the folded shape?

**Comment by uxder** [comment]
Yeah can you write it? (Hehe)

**Comment by andrewplummer** [comment]
No! That's left as an exercise for the users!!  >:P

**Comment by uxder** [comment]
I strongly feel this should be baked in as a feature of the library.

**Comment by andrewplummer** [comment]
ok let me have a look and get back to you

**Comment by uxder** [comment]
It's been a year....any progress on this bro? Hehe.
