### ISSUE TITLE
Cant drag with mouse, only finger touch

### ISSUE THREAD

**Issue by yadinYafe** [andrewplummer/peel-js#4]
Hello there!
This plugin so good and i love it! thanks for the work.

I just have one problem that i cant drag with regular mouse and just with finger.
think you know what is the problem??

thanks!
Yadin yafe.

**Comment by andrewplummer** [comment]
Does that include the examples on the [main page](https://andrewplummer.github.io/peel-js/)? Can you let me know how you set it up?

**Comment by yadinYafe** [comment]
It was worked from the first time , i accidentally disable it.
thanks for the quick response!
you can close the issue

**Comment by andrewplummer** [comment]
no worries!
